ln -sf $(pwd)/.vim ~/.config/nvim
ln -sf $(pwd)/.vim ~/.vim
ln -sf $(pwd)/.config/wezterm ~/.config/wezterm
ln -sf $(pwd)/.config/kitty ~/.config/kitty
ln -sf $(pwd)/.config/lazygit ~/.config/lazygit
ln -sf $(pwd)/.config/starship.toml ~/.config/starship.toml
ln -sf $(pwd)/.tmux.conf ~/.tmux.conf
ln -sf $(pwd)/.config/alacritty ~/.config/alacritty
ln -sf $(pwd)/.pyrightconfig.json ~/.pyrightconfig.json
